apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
  labels:
    app: python-app
spec:
  replicas: 3  # Number of pod replicas
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app-container
        image: thiagu95/python_app:1.0  # Replace with your Docker image
        ports:
        - containerPort: 5000  # The port your application runs on
        env:
        - name: ENVIRONMENT
          value: "production"  # Example environment variable

