apiVersion: v1
kind: Service
metadata:
  name: python-app-svc
  labels:
    app: python-app
spec:
  type: NodePort
  selector:
    app: python-app
  ports:
    - protocol: TCP
      port: 5000          # Port on which the service is exposed
      targetPort: 5000  # Port on which the application container is listening

